# Generated by Django 5.1.1 on 2024-10-14 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('passwordTag', models.CharField(blank=True, max_length=15)),
                ('description', models.TextField(blank=True)),
                ('dateSaved', models.DateTimeField(auto_now_add=True)),
                ('shared', models.BooleanField(blank=True, default=False)),
                ('sharedWith', models.ManyToManyField(related_name='shared_passwords', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_passwords', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
