# Generated by Django 5.1.1 on 2024-10-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsadmin', '0003_alter_password_sharedwith'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='password',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
