# Generated by Django 5.1.1 on 2024-11-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsadmin', '0004_alter_password_name_alter_password_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
